### ISSUE TITLE
Can't install from zip

### ISSUE THREAD

**Issue by chrisranderson** [rapidlasso/LAStoolsPluginQGIS3#1]
Here's the error report:

```lisp
An error has occurred while executing Python code: 

TypeError: QgsProcessingParameterFileDestination(): arguments did not match any overloaded call:   overload 1: too many arguments   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "....../QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStoolsPipelines\flightlinesToMergedCHM_SpikeFree.py", line 49, in initAlgorithm
    self.addParametersRasterOutputGUI()
  File "....../QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStoolsAlgorithm.py", line 269, in addParametersRasterOutputGUI
    self.addParameter(QgsProcessingParameterFileDestination(LAStoolsAlgorithm.OUTPUT_RASTER, "Output raster file", "tif", "", True, False))
TypeError: QgsProcessingParameterFileDestination(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'str'

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.2-Girona Girona, 307d082e3d 
```

I also couldn't see LASTools when searching for it from within QGIS, hence why I'm installing from the zip.

**Comment by rapidlasso** [comment]
Minimum requirement: QGIS 3.2 ... (-:

**Comment by chrisranderson** [comment]
An LAS file, yeah. 3.2 works just fine.
