### ISSUE TITLE
Erro utf-8 when the .las files path contains special characters like (Ç~´)

### ISSUE THREAD

**Issue by heyarth** [rapidlasso/LAStoolsPluginQGIS3#11]
Hi,
When i try use the plugin and chose a file in path with special characters, QGIS return with msg:

LAStools command line
C:/LAStools\bin\lasview -i "R:\FTP\07 Geração do Modelo Digital de Superfície\LOTE-01\MDS\SC-24-Z-D-I-2-NE-A-I-4-D.las" -points 5000000
LAStools console output
Traceback (most recent call last):
File "C:\Users/56565464/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStools\lasview.py", line 67, in processAlgorithm
LAStoolsUtils.runLAStools(commands, feedback)
File "C:\Users/56565464/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStoolsUtils.py", line 61, in runLAStools
feedback.pushConsoleInfo(output.decode("UTF-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 90: invalid continuation byte

Execution failed after 0.41 segundostion 90: invalid continuation byte

Note 1: I use windows 10 Pro 20h2.
Note 2: I tested the plugin with Windows 11 and work without errors.

**Comment by tangerren** [comment]
me too

**Comment by MPARIS90** [comment]
hello,

this error appear when you have special characters in your path. rename your different folders without space and special characters.

**Comment by BB-Heidelberg** [comment]
special characters are supported with latest version
