### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by raphidoc** [rapidlasso/LAStoolsPluginQGIS3#5]
Hello
When I try to run any tool with the .las entry, I receive this message:

```
Traceback (most recent call last):
File "C:/Users/Raphael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStools\lasground.py", line 75, in processAlgorithm
LAStoolsUtils.runLAStools(commands, feedback)
File "C:/Users/Raphael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStoolsUtils.py", line 61, in runLAStools
feedback.pushConsoleInfo(output.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 15: invalid start byte
```

I try different data source (usgs and government of quebec) but the same message appears.
Any idea to help ?
Thanks

**Comment by rapidlasso** [comment]
No idea. I would need a lot more detail on what are you **exactly** doing. And which QGIS version.
